### ISSUE TITLE
Error inflating class com.kizitonwose.calendar.view.WeekCalendarView

### ISSUE THREAD

**Issue by SandeepBaghelAlgo** [kizitonwose/Calendar#430]
### Library information:
 - Version: 2.0.1
 - View or Compose module: View

### Describe the bug**
 <FrameLayout
            android:id="@+id/fl_calendars"
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

            <com.kizitonwose.calendar.view.CalendarView
                android:id="@+id/month_calendar_view"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:cv_dayViewResource="@layout/custom_calender_day" />

            <com.kizitonwose.calendar.view.WeekCalendarView
                android:id="@+id/week_calendar_view"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:cv_dayViewResource="@layout/custom_calender_day" />
</FrameLayout>

FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example/com.example..JobListActivity}: android.view.InflateException: Binary XML file line #122 in com.example:layout/activity_job_list: Binary XML file line #122 in com.example:layout/activity_job_list: Error inflating class com.kizitonwose.calendar.view.WeekCalendarView
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4035)                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4201)                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)  
at android.app.ActivityThread.main(ActivityThread.java:8663)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: android.view.InflateException: Binary XML file line #122 in com.example:layout/activity_job_list: Binary XML file line #122 in com.example:layout/activity_job_list: Error inflating class com.kizitonwose.calendar.view.WeekCalendarView
Caused by: android.view.InflateException: Binary XML file line #122 in com.example:layout/activity_job_list: Error inflating class com.kizitonwose.calendar.view.WeekCalendarView
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Constructor.newInstance0(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
at android.view.LayoutInflater.createView(LayoutInflater.java:858)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:710)
at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
at androidx.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:303)
at androidx.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:284)
at com.example.base.BaseActivity.onCreate(BaseActivity.kt:68)
at android.app.Activity.performCreate(Activity.java:8290)
at android.app.Activity.performCreate(Activity.java:8270)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4009)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4201)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8663)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

Caused by: java.lang.IllegalStateException: No value set for `cv_dayViewResource` attribute.
at com.kizitonwose.calendar.view.WeekCalendarView.init(WeekCalendarView.kt:198)
at com.kizitonwose.calendar.view.WeekCalendarView.<init>(WeekCalendarView.kt:160)
... 33 more

**Caused by: java.lang.IllegalStateException: No value set for `cv_dayViewResource` attribute.**

I have done exactly same as you have shown in sample code, but still getting this exception. Please suggest the way to remove the exception. 
Thanks in advance!

**Comment by SandeepBaghelAlgo** [comment]
Issue Solved:
Just change **R.styleable.CalendarView** to **R.styleable.WeekCalendarView** in WeekCalendarView class.

private fun init(attributeSet: AttributeSet, defStyleAttr: Int, defStyleRes: Int) {
        if (isInEditMode) return
        itemAnimator = null
        setHasFixedSize(true)
        context.withStyledAttributes(
            attributeSet,
            **R.styleable.WeekCalendarView**,
            defStyleAttr,
            defStyleRes,
        ) {
            dayViewResource = getResourceId(
                R.styleable.WeekCalendarView_cv_dayViewResource,
                dayViewResource,
            )
...
...
}
