### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException: null cannot be cast to non-null type com.kizitonwose.calendarview.ui.CalendarAdapter

### ISSUE THREAD

**Issue by akrulec** [kizitonwose/Calendar#443]
### Library information:
 - Version:1.1.0
 - View or Compose module: View

### Describe the bug**
I see the following in the Firebase crashlytics:

```
Fatal Exception: java.lang.NullPointerException: null cannot be cast to non-null type com.kizitonwose.calendarview.ui.CalendarAdapter
       at com.kizitonwose.calendarview.ui.CalendarLayoutManager.getAdapter(CalendarLayoutManager.kt:20)
       at com.kizitonwose.calendarview.ui.CalendarLayoutManager.scrollToDay$lambda-1(CalendarLayoutManager.kt:52)
       at com.kizitonwose.calendarview.ui.CalendarLayoutManager.$r8$lambda$FFR7i7z7iaJlJsw0FeV84nJMvMM(CalendarLayoutManager.kt)
       at com.kizitonwose.calendarview.ui.CalendarLayoutManager$$InternalSyntheticLambda$3$40ff35232b54ab58a2998c15ede860cb95fc8da010355d6ebdc49df5be1c2b83$0.run(CalendarLayoutManager.java:2)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8633)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

### To Reproduce (if applicable)
Logged infrequently, but often enough as a FatalException in Firebase Crashlytics.

### Expected behavior (if applicable)
No error.

**Comment by kizitonwose** [comment]
Hey, I am not sure how to reproduce this, some steps would be nice. Additionally, there's been major improvements in version 2 to guard against crashes like this which could happen if `setupAsync` in v1 returns after the view is destroyed, maybe that's a possible fix?

I'd also advise checking that the calendar is not accessed before `setupAsync` finishes.

**Comment by kizitonwose** [comment]
I think it makes sense to close this, let me know if there's any other way I can help.

**Comment by akrulec** [comment]
I have tried upgrading the library, if I don't null adapter `onDestroyView`, I have a memory leak. If I do:
```
override fun onDestroyView() {
        super.onDestroyView()
        binding.weekCalendarView.adapter = null
        binding.weekCalendarView.layoutManager = null
        binding.weekCalendarView.weekScrollListener = null
        _binding = null
    }
```
then the error persists:
```
Fatal Exception: java.lang.NullPointerException: null cannot be cast to non-null type com.kizitonwose.calendar.view.internal.weekcalendar.WeekCalendarAdapter
       at com.kizitonwose.calendar.view.internal.weekcalendar.WeekCalendarLayoutManager.getAdapter(WeekCalendarLayoutManager.kt:13)
       at com.kizitonwose.calendar.view.internal.weekcalendar.WeekCalendarLayoutManager.notifyScrollListenerIfNeeded(WeekCalendarLayoutManager.kt)
       at com.kizitonwose.calendar.view.internal.CalendarLayoutManager.scrollToDay$lambda$1(CalendarLayoutManager.kt:49)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8757)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

My xml:
```
<layout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto">
    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content">
        <com.kizitonwose.calendar.view.WeekCalendarView
            android:id="@+id/week_calendar_view"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:cv_dayViewResource="@layout/item_view_calendar_day"
            app:cv_outDateStyle="endOfRow"
            app:cv_orientation="horizontal"
            app:cv_scrollPaged="true"
            android:transitionGroup="true"
            android:transitionName="@{@string/calendar_week_transition_name}"/>
    </RelativeLayout>
</layout>
```
Fragment class:
```
class WeekCalendarFragment : Fragment(R.layout.fragment_calendar_week) {
private var _binding: FragmentCalendarWeekBinding? = null
    // This property is only valid between onCreateView and onDestroyView.
    private val binding
        get() = _binding!!
    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        _binding = FragmentCalendarWeekBinding.bind(view)
    ....
    }
```

Thanks

**Comment by akrulec** [comment]
Looks like 6 devices in the Prelaunch report in Google Play hit the same error:
```
Exception Process: com.mycopilot.copilotapp, PID: 5254
java.lang.NullPointerException: null cannot be cast to non-null type com.kizitonwose.calendar.view.internal.weekcalendar.WeekCalendarAdapter
  at com.kizitonwose.calendar.view.internal.weekcalendar.WeekCalendarLayoutManager.getAdapter (WeekCalendarLayoutManager.kt)
  at com.kizitonwose.calendar.view.internal.weekcalendar.WeekCalendarLayoutManager.notifyScrollListenerIfNeeded (WeekCalendarLayoutManager.kt)
  at com.kizitonwose.calendar.view.internal.CalendarLayoutManager.scrollToDay$lambda$1 (CalendarLayoutManager.kt)
  at android.os.Handler.handleCallback (Handler.java:883)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at android.os.Looper.loop (Looper.java:237)
  at android.app.ActivityThread.main (ActivityThread.java:8016)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:496)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1076)
```

Any ideas how to fix this? I cannot afford a memory leak.

**Comment by kizitonwose** [comment]
@akrulec is it possible to share the information on the leak? If using LeakCanary, there is a timeline on the leak info page that could be useful.

**Comment by akrulec** [comment]
Ok, so I see another crash now:
```
java.util.NoSuchElementException: Collection contains no element matching the predicate.
    com.kizitonwose.calendar.view.internal.weekcalendar.WeekCalendarAdapter.reloadDay(WeekCalendarAdapter.kt:197)
    com.kizitonwose.calendar.view.WeekCalendarView.notifyDateChanged(WeekCalendarView.kt:299)
    com.mycopilot.copilotapp.ui.today.calendar.WeekCalendarFragment$onViewCreated$6.invoke(WeekCalendarFragment.kt:132)
```
I can add a try/catch in here, but I don't this should be a throw exception kind of failure. Thanks!

I have removed the nullifying of the adapter/scrolllistener/layoutmanager. LeakCanary seems to be happy.
