### ISSUE TITLE
Crash when user swipes in left or right direction to change the current month

### ISSUE THREAD

**Issue by DenisDavidek** [kizitonwose/Calendar#459]
Hi,
first of all, I would like to thank you and all of the contributors for this awesome library. Keep doing the great work.
Unfortunately, I found this bug:

### Library information:
-Version: 2.2.0
 - Compose module
 

### Describe the bug**
I recently updated to the stable release of Compose UI 1.4.0. I am using HorizontalCalendar with userScrollEnabled = true and calendarScrollPaged = true. Unfortunately, when I swipe left or right to change the month the app immediately crashes. Here is the stack trace:

                                                                                                    java.lang.AbstractMethodError: abstract method "float androidx.compose.foundation.gestures.snapping.SnapLayoutInfoProvider.calculateSnapStepSize(androidx.compose.ui.unit.Density)"
                                                                                                    	at androidx.compose.foundation.gestures.snapping.SnapFlingBehavior.isDecayApproachPossible(SnapFlingBehavior.kt:239)
                                                                                                    	at androidx.compose.foundation.gestures.snapping.SnapFlingBehavior.runApproach(SnapFlingBehavior.kt:209)
                                                                                                    	at androidx.compose.foundation.gestures.snapping.SnapFlingBehavior.longSnap(SnapFlingBehavior.kt:179)
                                                                                                    	at androidx.compose.foundation.gestures.snapping.SnapFlingBehavior.access$longSnap(SnapFlingBehavior.kt:83)
                                                                                                    	at androidx.compose.foundation.gestures.snapping.SnapFlingBehavior$fling$result$1.invokeSuspend(SnapFlingBehavior.kt:138)
                                                                                                    	at androidx.compose.foundation.gestures.snapping.SnapFlingBehavior$fling$result$1.invoke(Unknown Source:8)
                                                                                                    	at androidx.compose.foundation.gestures.snapping.SnapFlingBehavior$fling$result$1.invoke(Unknown Source:4)
                                                                                                    	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
                                                                                                    	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
                                                                                                    	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
                                                                                                    	at androidx.compose.foundation.gestures.snapping.SnapFlingBehavior.fling(SnapFlingBehavior.kt:134)
                                                                                                    	at androidx.compose.foundation.gestures.snapping.SnapFlingBehavior.access$fling(SnapFlingBehavior.kt:83)
                                                                                                    	at androidx.compose.foundation.gestures.snapping.SnapFlingBehavior$performFling$4.invokeSuspend(SnapFlingBehavior.kt:119)
                                                                                                    	at androidx.compose.foundation.gestures.snapping.SnapFlingBehavior$performFling$4.invoke(Unknown Source:8)
                                                                                                    	at androidx.compose.foundation.gestures.snapping.SnapFlingBehavior$performFling$4.invoke(Unknown Source:4)
                                                                                                    	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
                                                                                                    	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
                                                                                                    	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
                                                                                                    	at androidx.compose.foundation.gestures.snapping.SnapFlingBehavior.performFling(SnapFlingBehavior.kt:118)
                                                                                                    	at androidx.compose.foundation.gestures.snapping.SnapFlingBehavior.performFling(SnapFlingBehavior.kt:97)
                                                                                                    	at androidx.compose.foundation.gestures.ScrollingLogic$doFlingAnimation$2.invokeSuspend(Scrollable.kt:474)
                                                                                                    	at androidx.compose.foundation.gestures.ScrollingLogic$doFlingAnimation$2.invoke(Unknown Source:8)
                                                                                                    	at androidx.compose.foundation.gestures.ScrollingLogic$doFlingAnimation$2.invoke(Unknown Source:4)
                                                                                                    	at androidx.compose.foundation.gestures.DefaultScrollableState$scroll$2$1.invokeSuspend(ScrollableState.kt:178)
                                                                                                    	at androidx.compose.foundation.gestures.DefaultScrollableState$scroll$2$1.invoke(Unknown Source:8)
                                                                                                    	at androidx.compose.foundation.gestures.DefaultScrollableState$scroll$2$1.invoke(Unknown Source:4)
                                                                                                    	at androidx.compose.foundation.MutatorMutex$mutateWith$2.invokeSuspend(MutatorMutex.kt:160)
                                                                                                    	at androidx.compose.foundation.MutatorMutex$mutateWith$2.invoke(Unknown Source:8)
                                                                                                    	at androidx.compose.foundation.MutatorMutex$mutateWith$2.invoke(Unknown Source:4)
                                                                                                    	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
                                                                                                    	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
                                                                                                    	at androidx.compose.foundation.MutatorMutex.mutateWith(MutatorMutex.kt:153)
                                                                                                    	at androidx.compose.foundation.gestures.DefaultScrollableState$scroll$2.invokeSuspend(ScrollableState.kt:175)
                                                                                                    	at androidx.compose.foundation.gestures.DefaultScrollableState$scroll$2.invoke(Unknown Source:8)
                                                                                                    	at androidx.compose.foundation.gestures.DefaultScrollableState$scroll$2.invoke(Unknown Source:4)
                                                                                                    	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
                                                                                                    	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
                                                                                                    	at androidx.compose.foundation.gestures.DefaultScrollableState.scroll(ScrollableState.kt:174)
																										at androidx.compose.foundation.lazy.LazyListState.scroll(LazyListState.kt:262)
                                                                                                    	at androidx.compose.foundation.gestures.ScrollableState.scroll$default(ScrollableState.kt:53)
                                                                                                    	at androidx.compose.foundation.gestures.ScrollingLogic.doFlingAnimation-QWom1Mo(Scrollable.kt:462)
                                                                                                    	at androidx.compose.foundation.gestures.ScrollingLogic.onDragStopped-sF-c-tU(Scrollable.kt:445)
                                                                                                    	at androidx.compose.foundation.gestures.ScrollableKt$pointerScrollable$3$1$1.invokeSuspend(Scrollable.kt:285)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:68)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:997)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:797)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:728)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:883)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at android.os.Looper.loop(Looper.java:237)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8167)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
                                                                                                    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@58c013f, androidx.compose.runtime.BroadcastFrameClock@ab7ea0c, StandaloneCoroutine{Cancelling}@ae67f55, AndroidUiDispatcher@fae4d6a]

I tried to downgrade back to Compose UI 1.3. The horizontal Calendar works as expected. Looks like Google changed something in Compose UI 1.4 which the current stable library version does not count with.

### To Reproduce (if applicable)
1. Create a new Android project with Empty Compose Activity
2. Update all libraries to the latest version (compose libraries to version 1.4.0)
3. Copy the code from your compose sample - example 3 screen
4. Launch the app on the emulator and swipe left or right on the horizontal Calendar

### Expected behaviour (if applicable)
I was hoping to see the same behaviour on the latest compose library 1.3 versions. So after swiping the current month changes to the next or previous without crashing depending on the direction you have swiped.

### Additional information
I see that you do have a new snapshot version of this library. Are you currently working on the compose UI 1.4 integration?

**Comment by kizitonwose** [comment]
Version 2.3.0 is now released with the fix.
