### ISSUE TITLE
Throw AbstractMethodError: abstract method "float androidx.compose.foundation.gestures.snapping.SnapLayoutInfoProvider.calculateSnappingOffset(float) when scrolling calendar

### ISSUE THREAD

**Issue by tuanpv** [kizitonwose/Calendar#501]
Library information:

    Version: 2.4.0
Compose module: Compose
androidx.compose.foundation:foundation:1.6.0-alpha06
androidx.compose.foundation:foundation-android:1.6.0-alpha06

Describe the bug:

java.lang.AbstractMethodError: abstract method "float androidx.compose.foundation.gestures.snapping.SnapLayoutInfoProvider.calculateSnappingOffset(float)"
                                                                                                    	at androidx.compose.foundation.gestures.snapping.SnapFlingBehavior.shortSnap(SnapFlingBehavior.kt:143)
                                                                                                    	at androidx.compose.foundation.gestures.snapping.SnapFlingBehavior.access$shortSnap(SnapFlingBehavior.kt:79)
                                                                                                    	at androidx.compose.foundation.gestures.snapping.SnapFlingBehavior$fling$result$1.invokeSuspend(SnapFlingBehavior.kt:128)
                                                                                                    	at androidx.compose.foundation.gestures.snapping.SnapFlingBehavior$fling$result$1.invoke(Unknown Source:8)
                                                                                                    	at androidx.compose.foundation.gestures.snapping.SnapFlingBehavior$fling$result$1.invoke(Unknown Source:4)
                                                                                                    	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
                                                                                                    	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
                                                                                                    	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
                                                                                                    	at androidx.compose.foundation.gestures.snapping.SnapFlingBehavior.fling(SnapFlingBehavior.kt:126)
                                                                                                    	at androidx.compose.foundation.gestures.snapping.SnapFlingBehavior.performFling(SnapFlingBehavior.kt:112)
                                                                                                    	at androidx.compose.foundation.gestures.snapping.SnapFlingBehavior.performFling(SnapFlingBehavior.kt:91)
                                                                                                    	at androidx.compose.foundation.gestures.ScrollingLogic$doFlingAnimation$2.invokeSuspend(Scrollable.kt:844)
                                                                                                    	at androidx.compose.foundation.gestures.ScrollingLogic$doFlingAnimation$2.invoke(Unknown Source:8)
                                                                                                    	at androidx.compose.foundation.gestures.ScrollingLogic$doFlingAnimation$2.invoke(Unknown Source:4)
                                                                                                    	at androidx.compose.foundation.gestures.DefaultScrollableState$scroll$2$1.invokeSuspend(ScrollableState.kt:181)...

    Just scroll to next or prev month.

I have used compose-bom: 2023.09.01, and can see error happened in SnapLayoutInfoProvider androidx.compose.foundation:foundation-android:1.6.0-alpha06.

Any one can help, thank you so much.

**Comment by pcevikogullari** [comment]
Same here, couldn't find any solution.

**Comment by kizitonwose** [comment]
The library is not yet tested against 1.6.x as it is in alpha. I'll see if I can find the time this weekend.

<img width="291" alt="Screenshot 2023-11-03 at 09 56 40" src="https://github.com/kizitonwose/Calendar/assets/15170090/cd79ccb1-d8e7-442c-b381-8f5520e69057">

**Comment by tuanr365** [comment]
Thank you.
I know what is going on.
The reason is:
In androidx.compose.foundation:foundation:1.6.0-alpha06 version:
They Remove density from SnapFlingBehavior. All implementations of SnapLayoutInfoProvider already have a way of accessing the density, the receiver scope could be removed which will lead to a less complex implementation of both SnapFlingBehavior and SnapLayoutInfoProviders.

To fix it:
Open compose module, go to com.kizitonwose.calendar.compose.CalendarDefaults file and change:
override fun Density.calculateApproachOffset(initialVelocity: Float): Float = 0f
to
override fun calculateApproachOffset(initialVelocity: Float): Float = 0f

It working fine with stable version.
That's great if @kizitonwose you can also release wonderful lib in alpha version with my fix.

Thank you so much.

**Comment by kizitonwose** [comment]
@tuanr365 Good insight 👍🏼 

@tuanpv @pcevikogullari Support for compose 1.6.0 alpha is now available in [2.5.0-alpha01](https://github.com/kizitonwose/Calendar/releases/tag/2.5.0-alpha01)

**Comment by tuanr365** [comment]
@kizitonwose thank you so much.

**Comment by tuanpv** [comment]
@kizitonwose thank you.

**Comment by pcevikogullari** [comment]
@kizitonwose thank you for your efforts!

**Comment by yuri-0415** [comment]
@kizitonwose Thank you for solving this issue!!
