### ISSUE TITLE
Crash using Compose BOM 2024-02-00

### ISSUE THREAD

**Issue by benoitletondor** [kizitonwose/Calendar#532]
### Library information:
 - Version: 2.4.1
 - View or Compose module: 1.6.1
 
### Describe the bug**
Crash on Horizontal calendar when swiping left or right to change month. The bug is fixed in `2.5.0-beta01` version but it's still a beta build.

### To Reproduce (if applicable)
1. Swipe left or right

### Additional information

Crash log:

```
FATAL EXCEPTION: main
                                                                                                    java.lang.AbstractMethodError: abstract method "float androidx.compose.foundation.gestures.snapping.SnapLayoutInfoProvider.calculateApproachOffset(float)"
                                                                                                    	at androidx.compose.foundation.gestures.snapping.SnapFlingBehavior$fling$result$1.invokeSuspend(SnapFlingBehavior.kt:167)
                                                                                                    	at androidx.compose.foundation.gestures.snapping.SnapFlingBehavior$fling$result$1.invoke(Unknown Source:8)
                                                                                                    	at androidx.compose.foundation.gestures.snapping.SnapFlingBehavior$fling$result$1.invoke(Unknown Source:4)
                                                                                                    	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
                                                                                                    	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
                                                                                                    	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
                                                                                                    	at androidx.compose.foundation.gestures.snapping.SnapFlingBehavior.fling(SnapFlingBehavior.kt:165)
                                                                                                    	at androidx.compose.foundation.gestures.snapping.SnapFlingBehavior.performFling(SnapFlingBehavior.kt:151)
                                                                                                    	at androidx.compose.foundation.gestures.snapping.SnapFlingBehavior.performFling(SnapFlingBehavior.kt:130)
                                                                                                    	at androidx.compose.foundation.gestures.ScrollingLogic$doFlingAnimation$2.invokeSuspend(Scrollable.kt:844)
                                                                                                    	at androidx.compose.foundation.gestures.ScrollingLogic$doFlingAnimation$2.invoke(Unknown Source:8)
                                                                                                    	at androidx.compose.foundation.gestures.ScrollingLogic$doFlingAnimation$2.invoke(Unknown Source:4)
                                                                                                    	at androidx.compose.foundation.gestures.DefaultScrollableState$scroll$2$1.invokeSuspend(ScrollableState.kt:181)
                                                                                                    	at androidx.compose.foundation.gestures.DefaultScrollableState$scroll$2$1.invoke(Unknown Source:8)
                                                                                                    	at androidx.compose.foundation.gestures.DefaultScrollableState$scroll$2$1.invoke(Unknown Source:4)
                                                                                                    	at androidx.compose.foundation.MutatorMutex$mutateWith$2.invokeSuspend(MutatorMutex.kt:173)
                                                                                                    	at androidx.compose.foundation.MutatorMutex$mutateWith$2.invoke(Unknown Source:8)
                                                                                                    	at androidx.compose.foundation.MutatorMutex$mutateWith$2.invoke(Unknown Source:4)
                                                                                                    	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
                                                                                                    	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
                                                                                                    	at androidx.compose.foundation.MutatorMutex.mutateWith(MutatorMutex.kt:166)
                                                                                                    	at androidx.compose.foundation.gestures.DefaultScrollableState$scroll$2.invokeSuspend(ScrollableState.kt:178)
                                                                                                    	at androidx.compose.foundation.gestures.DefaultScrollableState$scroll$2.invoke(Unknown Source:8)
                                                                                                    	at androidx.compose.foundation.gestures.DefaultScrollableState$scroll$2.invoke(Unknown Source:4)
                                                                                                    	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
                                                                                                    	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
                                                                                                    	at androidx.compose.foundation.gestures.DefaultScrollableState.scroll(ScrollableState.kt:177)
                                                                                                    	at androidx.compose.foundation.lazy.LazyListState.scroll(LazyListState.kt:295)
                                                                                                    	at androidx.compose.foundation.gestures.ScrollableState.scroll$default(ScrollableState.kt:53)
                                                                                                    	at androidx.compose.foundation.gestures.ScrollingLogic.doFlingAnimation-QWom1Mo(Scrollable.kt:831)
                                                                                                    	at androidx.compose.foundation.gestures.ScrollingLogic$onDragStopped$performFling$1.invokeSuspend(Scrollable.kt:807)
                                                                                                    	at androidx.compose.foundation.gestures.ScrollingLogic$onDragStopped$performFling$1.invoke-sF-c-tU(Unknown Source:12)
                                                                                                    	at androidx.compose.foundation.gestures.ScrollingLogic$onDragStopped$performFling$1.invoke(Unknown Source:10)
                                                                                                    	at androidx.compose.foundation.AndroidEdgeEffectOverscrollEffect.applyToFling-BMRW4eQ(AndroidOverscroll.android.kt:248)
                                                                                                    	at androidx.compose.foundation.gestures.ScrollingLogic.onDragStopped-sF-c-tU(Scrollable.kt:820)
                                                                                                    	at androidx.compose.foundation.gestures.ScrollableGesturesNode$onDragStopped$1$1.invokeSuspend(Scrollable.kt:612)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
```

**Comment by kizitonwose** [comment]
Please use version [2.5.0](https://github.com/kizitonwose/Calendar/releases/tag/2.5.0)
