### ISSUE TITLE
Exception after updating dependencies Compose 1.7.0-beta01 Kotlin 1.9.24

### ISSUE THREAD

**Issue by Efimj** [kizitonwose/Calendar#547]
### Library information:
 - Version: 2.5.1
 - Compose

### Describe the bug
**After updating dependencies**

```
    compose_version = '1.7.0-beta01'
    implementation "androidx.compose.animation:animation:$compose_version"
    implementation "androidx.compose.foundation:foundation:$compose_version"

    plugin:
    id 'org.jetbrains.kotlin.android' version '1.9.24' apply false
```

**Exception in calendars**
```
 java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/compose/foundation/gestures/snapping/SnapPositionInLayout;
                                                                                                    	at com.kizitonwose.calendar.compose.CalendarDefaultsKt.access$CalendarSnapPositionInLayout(CalendarDefaults.kt:1)
                                                                                                    	at com.kizitonwose.calendar.compose.CalendarDefaults.pagedFlingBehavior(CalendarDefaults.kt:25)
                                                                                                    	at com.kizitonwose.calendar.compose.CalendarDefaults.flingBehavior(CalendarDefaults.kt:36)
                                                                                                    	at com.kizitonwose.calendar.compose.CalendarKt.Calendar(Calendar.kt:173)
                                                                                                    	at com.kizitonwose.calendar.compose.CalendarKt.HorizontalCalendar(Calendar.kt:74)
```

**Comment by kizitonwose** [comment]
Compose 1.7.0-beta01 support is now available in version [2.6.0-beta01](https://github.com/kizitonwose/Calendar/releases/tag/2.6.0-beta01)

**Comment by Efimj** [comment]
Thanks for your work 💜

**Comment by D35P4C1T0** [comment]
I'm also facing the same issue with
- Compose 1.6.8
- Kotlin 1.9.24
- Calendar-compose 2.5.2

### Exception in Calendar
```
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/compose/foundation/gestures/snapping/SnapPositionInLayout;
        	at com.kizitonwose.calendar.compose.CalendarDefaultsKt.access$CalendarSnapPositionInLayout(CalendarDefaults.kt:1)
                at com.kizitonwose.calendar.compose.CalendarDefaults.pagedFlingBehavior(CalendarDefaults.kt:25)
                at com.kizitonwose.calendar.compose.CalendarDefaults.flingBehavior(CalendarDefaults.kt:36)
                at com.kizitonwose.calendar.compose.CalendarKt.Calendar(Calendar.kt:173)
                at com.kizitonwose.calendar.compose.CalendarKt.HorizontalCalendar(Calendar.kt:74)                                                                                           	
```
